/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f0e42c30-fcd7-4e05-a810-e0566f39f5fa",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_71UsD1skO",
    "aws_user_pools_web_client_id": "23g6kk2a9k53ochc5le848gfrc",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "api75996003",
            "endpoint": "https://9xu5b3oocg.execute-api.us-east-1.amazonaws.com/env",
            "region": "us-east-1"
        }
    ],
    "aws_content_delivery_bucket": "reactamplified-20200429081254-hostingbucket-env",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d3niie3w5fztox.cloudfront.net"
};


export default awsmobile;
